import type { Metadata } from "next";
import { Geist } from "next/font/google";
import type { ReactNode } from "react";
import "../globals.css";
import localFont from "next/font/local";
import { Header } from "./_components/header";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
  display: "swap",
});

const estedad = localFont({
  src: "../../public/estedad.woff2",
  variable: "--font-estedad",
  preload: true,
  display: "swap",
});

export const metadata: Metadata = {
  title: "Coding developer",
  description: "Generated by create next app",
};

export default function LandingLayout({ children }: { children: ReactNode }) {
  return (
    <html lang="en" dir="rtl" data-scroll-behavior="smooth">
      <body className={`${geistSans.variable} ${estedad.variable}`}>
        <Header />
        {children}
      </body>
    </html>
  );
}
