import type { Metadata } from "next";
import { Geist } from "next/font/google";
import type { ReactNode } from "react";
import "../globals.css";
import localFont from "next/font/local";
import Image from "next/image";
import Link from "next/link";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
  display: "swap",
});

const estedad = localFont({
  src: "../../public/estedad.woff2",
  preload: true,
  variable: "--font-estedad",
  display: "swap",
});

export const metadata: Metadata = {
  title: "Coding developer",
  description: "Generated by create next app",
};

export default function AuthLayout({ children }: { children: ReactNode }) {
  return (
    <html lang="en" dir="rtl" data-scroll-behavior="smooth">
      <body
        className={`${geistSans.variable} ${estedad.variable} grid min-h-svh gap-4 p-4 lg:grid-cols-2`}
      >
        <section className="relative hidden overflow-hidden rounded-xl lg:block">
          <Image
            src="/code-unsplash.jpg"
            alt="Image"
            width={6336}
            height={9504}
            priority
            className="absolute inset-0 h-full w-full object-cover"
          />
        </section>

        <section className="flex flex-col">
          <Link href="/" className="self-center">
            <Image
              src="/GPTlogo.svg"
              alt="logo"
              width={150}
              height={150}
              className="h-[150px] w-[150px]"
            />
          </Link>
          <div className="flex flex-1 items-center justify-center">
            {children}
          </div>
        </section>
      </body>
    </html>
  );
}
